mesh_files:
  base:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/visual/base.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/visual/waist.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/collision/waist.stl

  upper_arm:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/visual/arm_01.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/collision/arm_01.stl
      mesh_files:

  forearm:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/visual/arm_02.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/collision/arm_02.stl

  wrist_1:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/visual/arm_03.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/arm/collision/arm_03.stl
    visual_offset: -0.093

  wrist_2:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/ur5/visual/wrist2.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/ur5/collision/wrist2.stl
    visual_offset: -0.095

  wrist_3:
    visual:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/ur5/visual/wrist3.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: multi_robot_arm
        path: urdf/ur/meshes/ur5/collision/wrist3.stl
    visual_offset: -0.0818
